name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Pull Oracle 24 JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '24'
    - name: check JVM install
      run: javac -version
    - name: Install leiningen
      uses: ./
      with:
        lein: 2.9.1
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check leiningen version
      run: lein version
