name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Pull Oracle 21 JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        version: '21'
    - name: check JVM install 
      run: javac -version 
